from __future__ import annotations

import re
from .models import Candidate


def q(s: str) -> str:
    return '"' + str(s).replace('\\', '\\\\').replace('\n', '\\n').replace('\r', '').replace('"', '\\"') + '"'


def pem(lines: list[str], key: str, value: str, indent: str = "    "):
    lines.append(f"{indent}{key}: |")
    for line in value.strip().splitlines():
        lines.append(f"{indent}  {line}")


def _node_name(c: Candidate, tier: str, index: int) -> str:
    isp = (c.intel.get("isp") or c.intel.get("org") or c.source_family)[:24]
    isp = re.sub(r"[^A-Za-z0-9 ._-]+", "-", str(isp)).strip() or c.source_family
    return f"US-{tier}{index:02d}-{isp}".replace(":", "-")


def _proxy_lines(c: Candidate, name: str) -> list[str]:
    p = c.profile
    lines = [
        f"  - name: {q(name)}",
        "    type: openvpn",
        f"    server: {q(p.server)}",
        f"    port: {p.port}",
        f"    proto: {p.proto}",
        f"    udp: {'true' if p.proto == 'udp' else 'false'}",
    ]
    if p.username:
        lines += [f"    username: {q(p.username)}", f"    password: {q(p.password)}"]
    pem(lines, "ca", p.ca)
    if p.cert and p.key:
        pem(lines, "cert", p.cert)
        pem(lines, "key", p.key)
    if p.cipher:
        lines.append(f"    cipher: {p.cipher}")
    if p.auth:
        lines.append(f"    auth: {p.auth}")
    if p.data_ciphers:
        lines.append("    data-ciphers: [" + ", ".join(p.data_ciphers) + "]")
        if p.cipher:
            lines.append(f"    data-ciphers-fallback: {p.cipher}")
    if p.tls_auth:
        pem(lines, "tls-auth", p.tls_auth)
        if p.key_direction:
            lines.append(f"    key-direction: {q(p.key_direction)}")
    if p.tls_crypt:
        pem(lines, "tls-crypt", p.tls_crypt)
    if p.tls_crypt_v2:
        pem(lines, "tls-crypt-v2", p.tls_crypt_v2)
    if p.comp_lzo:
        lines.append(f"    comp-lzo: {q(p.comp_lzo)}")
    if p.ping:
        lines.append(f"    ping: {p.ping}")
    if p.ping_restart:
        lines.append(f"    ping-restart: {p.ping_restart}")
    return lines


def render_probe_config(candidates: list[Candidate], ports: list[int], direct_port: int) -> str:
    """Loopback listeners that each pin their traffic to one candidate, plus a DIRECT control listener."""
    names = [f"probe-{i}" for i in range(len(candidates))]
    lines = ["log-level: warning", "ipv6: false", "proxies:"]
    for c, name in zip(candidates, names):
        lines += _proxy_lines(c, name)
    lines.append("listeners:")
    for i, (proxy, port) in enumerate([("DIRECT", direct_port), *zip(names, ports)]):
        lines += [
            f"  - name: in-{i}",
            "    type: mixed",
            "    listen: 127.0.0.1",
            f"    port: {port}",
            f"    proxy: {q(proxy)}",
        ]
    return "\n".join(lines) + "\n"


def render(preferred: list[Candidate], fallback: list[Candidate]) -> str:
    if not preferred and not fallback:
        raise ValueError("cannot render Mihomo YAML without nodes")

    lines = [
        "# Generated by gate-us-lite via GitHub Actions.",
        "# US-STABLE is the recommended group; preferred nodes are ordered before fallback nodes.",
        "proxies:",
    ]
    names: list[tuple[Candidate, str]] = []

    for idx, c in enumerate(preferred, 1):
        names.append((c, _node_name(c, "P", idx)))
    for idx, c in enumerate(fallback, 1):
        names.append((c, _node_name(c, "B", idx)))

    for c, name in names:
        lines += [*_proxy_lines(c, name), ""]

    pnames = [name for c, name in names if c in preferred]
    all_names = [name for _, name in names]

    lines += [
        "proxy-groups:",
        "  - name: US-PREFERRED",
        "    type: fallback",
        "    url: https://www.gstatic.com/generate_204",
        "    expected-status: 204",
        "    interval: 300",
        "    lazy: true",
        "    proxies:",
    ]
    lines += [f"      - {q(n)}" for n in (pnames or all_names)]
    lines += [
        "  - name: US-STABLE",
        "    type: fallback",
        "    url: https://www.gstatic.com/generate_204",
        "    expected-status: 204",
        "    interval: 300",
        "    lazy: true",
        "    proxies:",
    ]
    lines += [f"      - {q(n)}" for n in all_names]
    lines.append("")
    return "\n".join(lines)
